
version: 2.1
orbs:
  artifactory: sandbox/artifactory@volatile

workflows:
  test-orb:
    jobs:
      - upload-commands
      - artifactory/upload:
          name: Test Upload
          source: artifact.jar
          target: local-generic/jobfolder
          build-name: generic-artifact
          build-steps:
            - run: echo "not a jar" > artifact.jar
      - artifactory/docker-publish:
          name: Docker Publish
          docker-registry: orbdemos-docker-local.jfrog.io
          repository: docker-local
          docker-tag: orbdemos-docker-local.jfrog.io/hello-world-default:1.0-${CIRCLE_BUILD_NUM}
          pre-steps:
            - checkout
            - run: cp docker-publish-assets/Dockerfile .
      - artifactory/docker-publish:
          name: Docker Publish CustomBuild
          docker-registry: orbdemos-docker-local.jfrog.io
          repository: docker-local
          docker-tag: orbdemos-docker-local.jfrog.io/hello-world-custom:1.0-${CIRCLE_BUILD_NUM}
          docker-steps:
            - run: docker build -t orbdemos-docker-local.jfrog.io/hello-world:1.0-${CIRCLE_BUILD_NUM} docker-publish-assets

jobs:
  upload-commands:
    docker:
      - image: circleci/node:10
    steps:
      # These are the example steps for consuming the orb.
      - checkout
      - artifactory/install
      - artifactory/configure
      - run: echo "not a jar" >> artifact.jar
      - artifactory/upload:
          source: artifact.jar
          target: local-generic/commandfolder
          build-name: generic-artifact-command
          build-number: ${CIRCLE_BUILD_NUM}
      - artifactory/build-integration:
          build-name: generic-artifact-command
          build-number: ${CIRCLE_BUILD_NUM}

