
version: 2.1
orbs:
  artifactory: sandbox/artifactory@volatile

workflows:
  test-orb:
    jobs:
      - artifactory/upload:
          name: Test Upload
          source: artifact.jar
          target: local-generic/artifact.jar
          build-name: generic-artifact
          build-steps:
            - run: echo "not a jar" > artifact.jar
      - artifactory/docker-publish:
          name: Docker Publish
          docker-registry: orbdemos-docker.jfrog.io
          repository: docker
          build-name: hello-alpine
          docker-tag: orbdemos-docker.jfrog.io/hello-world-default:1.0-${CIRCLE_BUILD_NUM}
      - artifactory/docker-publish:
          name: Docker Publish with Jib
          docker-registry: orbdemos-docker.jfrog.io
          repository: docker
          build-name: hello-alpine-custom
          docker-tag: orbdemos-docker.jfrog.io/spring-boot:1.0-${CIRCLE_BUILD_NUM}
          docker-steps:
            - run: echo ${DOCKERTAG}
            - run: cd java && ./mvnw compile jib:exportDockerContext -s .mvn/wrapper/settings.xml
            - run: docker build -t ${DOCKERTAG} target/jib-docker-context


