
version: 2.1
orbs:
  artifactory: sandbox/artifactory@volatile

workflows:
  test-orb:
    jobs:
      - upload-commands
      - artifactory/upload:
          name: Test Upload
          source: artifact.jar
          target: local-generic/jobfolder
          build-name: generic-artifact
          build-steps:
            - run: echo "not a jar" > artifact.jar
      - artifactory/docker-publish:
          name: Docker Publish
          docker-registry: orbdemos-docker-local.jfrog.io
          repository: docker-local
          docker-tag: orbdemos-docker-local.jfrog.io/hello-world:1.0-${CIRCLE_BUILD_NUM}
          docker-steps:
            - run: docker pull hello-world
            - run: docker tag hello-world:latest orbdemos-docker-local.jfrog.io/hello-world:1.0-${CIRCLE_BUILD_NUM}

jobs:
  upload-commands:
    machine: true
    steps:
      # These are the example steps for consuming the orb.
      - checkout
      - artifactory/install
      - artifactory/configure
      - run: echo "not a jar" >> artifact.jar
      - artifactory/upload:
          source: artifact.jar
          target: local-generic/commandfolder
          build-name: generic-artifact
          build-number: ${CIRCLE_BUILD_NUM}
      - artifactory/build-integration:
          build-name: ${CIRCLE_PROJECT_REPONAME}
          build-number: ${CIRCLE_BUILD_NUM}

