
executors:
  with-artifactory:
    docker:
      image: circleci/openjdk:8
      image: docker.bintray.io/jfrog/artifactory-oss:latest

workflows:
  version: 2
  test-orb:
    jobs:
      - artifactory/upload:
          name: Test Upload
          source: test/artifact.jar
          target: repo/path
          build-steps:
            - run: mvn install -B
          pre-steps:
            - run: dockerize -wait tcp://localhost:8081 -timeout 1m
            - run: echo "export ARTIFACTORY_URL=http://localhost:8081/artifactory" >> $BASH_ENV
            - run: echo "export ARTIFACTORY_API_KEY=$(curl -uadmin:password -X POST http://localhost:8081/artifactory/api/security/apiKey)" >> $BASH_ENV
